FROM eclipse-temurin:26-jdk

WORKDIR /app

COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

COPY src src

CMD ["./mvnw", "-Dtest=ClientesAPITest", "test"]