spring.application.name=Kraus_ERP
spring.security.oauth2.client.registration.google.client-id=271938400907-rmvh051aahnm3b7g27c5ac9qis13ito6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost/ERP
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
